[character]
success_symbol = '\$'

[directory]
style = 'blue'

[git_branch]
disabled = false
style = 'white'
format = '[$symbol$branch(:$remote_branch)]($style) '

[git_status]
stashed = ""
style = "#FFA500" # simple orange

[golang]
disabled = true

[kubernetes]
format = '[☸](blue) ($cluster) \($namespace\) '
disabled = false
[[kubernetes.contexts]]
#{ context_pattern = '(?P<cluster>[^/]+$)', context_alias = "$cluster" }
context_pattern = 'arn.*:(?P<cluster>[\w/]+)'
context_alias = "$cluster"

[docker_context]
disabled=true

[aws]
disabled=true

[helm]
disabled=true

# Helm doesn't work well with non-standard version keys. Could enable again
# once the following is added: https://github.com/starship/starship/issues/6102
[package]
disabled=true

[cmd_duration]
min_time = 30_000
format = '\[[⏱ $duration]($style)\]'
style = 'yellow'

[custom.system_icons]
description = "Show system icons"
command     = '([ $(uname -s) == "Darwin" ] && echo ) || ([ $(uname -s) == "Linux" ] && echo )'
symbol      = "on"
format      = "[$output]($style) "
style       = "bold"
shell       = ["bash", "--noprofile", "--norc"]
when        = "true"
